# sign up
POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
    "name": "john",
    "email": "john_doe@mail.com",
    "password": "password"
}
###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "john_doe@mail.com",
    "password": "password"
}
### auth
###
GET http://localhost:5000/api/auth
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg

### profile
POST http://localhost:5000/api/profile/create
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg

{
    "company": "john_doe.inc",
    "website": "www.john_doe_web.com",
    "location": "Cairo, Egypt",
    "githubusername": "john doe",
    "twitter": "www.twitter.com/johnDoe",
    "facebook": "www.facebook.com/johnDoe",
    "youtube":"www.youtube.com/johnDoe",
    "linkedin": "www.linkedin.com/johnDoe",
    "instagram": "www.instagram.com/johnDoe",
    "skills": "html5, css3, javascript, react, redux, typescript",
    "status": "junior fullstack",
    "bio": "Hi, I am a full stack web developer"
}
###
GET http://localhost:5000/api/profile/me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg
###
GET http://localhost:5000/api/profile

###
GET http://localhost:5000/api/profile/user/5ee23d658bc9123bbce35ef5


###
DELETE http://localhost:5000/api/profile/delete
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMWRmZTQyOTU0YWUxNzYwNGMxZDk2In0sImlhdCI6MTU5MTg2NjMwMywiZXhwIjoxNTkyNDcxMTAzfQ.3mQeTjdbhp97P09wDAoTEgKOlIsCbVVVhjOi2g9Nu5k

###
PUT http://localhost:5000/api/profile/experience
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg

{
    "title": "junior front end developer",
    "company": "worcbox.inc",
    "location": "Cairo, Egypt",
    "from": "06-01-2020",
    "current": true,
    "description": "javascript developer handles and converts mocks into a fully function apps"
}

###
PUT http://localhost:5000/api/profile/education
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg

{
    "school": "MIT",
    "degree": "Good",
    "fieldofstudy": "C.S",
    "from": "01-07-2015",
    "current": false,
    "to": "01-07-2019"
}

###
POST http://localhost:5000/api/post/create
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg

{
    "text": "this is post no 1"
}

###
GET http://localhost:5000/api/posts
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg

###
GET http://localhost:5000/api/posts/5ee3bf8f07d9c849d4606d30
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg

###
DELETE  http://localhost:5000/api/posts/5ee3bfaa7b315d47981d7d4f
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWVlMjNkNjU4YmM5MTIzYmJjZTM1ZWY1In0sImlhdCI6MTU5MTg4NTE1NywiZXhwIjoxNTkyNDg5OTU3fQ.gzThB1cC-nuHAL5QWHEY7-Wxv_OS8mN-q3yTbxuoBZg


